service: jarjar-landing-back
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  region: ${self:custom.my-region}
  versionFunctions: true
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      allowedMethods:
        - OPTIONS
        - POST
        - GET
        - PUT
        - DELETE
      exposedResponseHeaders:
        - Content-Type
        - Authorization
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.stage}
    SMTP_HOST: webmail.holocruxe.com
    SMTP_PORT: 465
    SMTP_USER: contacto@holocruxe.com
    SMTP_FROM: contacto@holocruxe.com

    

package:
  exclude:
    - .env
    - _env/**
    - node_modules/**
    - package.json
    - package-lock.json
    - bun.lock
    - bun.lockb

custom:
  stage: ${opt:stage, 'dev'}
  my-region: ${opt:region, 'us-east-1'}
  config:
    dev:
      memorySize: 1024
      account_id: "891377228861"
    prod:
      memorySize: 1024
      account_id: "891377228861"

functions:
  post_contact_info:
    handler: handler.contact_handler
    role: arn:aws:iam::891377228861:role/lambda-auth-rol
    timeout: 30
    events:
      - httpApi:
          path: /contact
          method: post

plugins:
  - serverless-offline
  - serverless-python-requirements